export const DATASET_INFO_PROCESS = 'DATASET_INFO_PROCESS'
export const DATASET_ERROR_PROCESS = 'DATASET_ERROR_PROCESS'

export const DATASET_BASICINFO_BY_ID_INFO_PROCESS = 'DATASET_BASICINFO_BY_ID_INFO_PROCESS'
export const DATASET_BASICINFO_BY_ID_ERROR_PROCESS = 'DATASET_BASICINFO_BY_ID_ERROR_PROCESS'

export const DATASET_MEASURES_BY_ID_INFO_PROCESS = 'DATASET_MEASURES_BY_ID_INFO_PROCESS'
export const DATASET_MEASURES_BY_ID_ERROR_PROCESS = 'DATASET_MEASURES_BY_ID_ERROR_PROCESS'

export const DATASET_FILEPATHS_BY_ID_INFO_PROCESS = 'DATASET_FILEPATHS_BY_ID_INFO_PROCESS'
export const DATASET_FILEPATHS_BY_ID_ERROR_PROCESS = 'DATASET_FILEPATHS_BY_ID_ERROR_PROCESS'

export const SUBJECT_ALL_ROIS_INFO_PROCESS = 'SUBJECT_ALL_ROIS_INFO_PROCESS'
export const SUBJECT_ALL_ROIS_ERROR_PROCESS = 'SUBJECT_ALL_ROIS_ERROR_PROCESS'

export const SUBJECT_ROIS_INFO_PROCESS = 'SUBJECT_ROIS_INFO_PROCESS'
export const SUBJECT_ROIS_ERROR_PROCESS = 'SUBJECT_ROIS_ERROR_PROCESS'

export const SUBJECT_ALL_FILES_INFO_PROCESS = 'SUBJECT_ALL_FILES_INFO_PROCESS'
export const SUBJECT_ALL_FILES_ERROR_PROCESS = 'SUBJECT_ALL_FILES_ERROR_PROCESS'


export const SUBJECT_FILES_INFO_PROCESS = 'SUBJECT_FILES_INFO_PROCESS'
export const SUBJECT_FILES_ERROR_PROCESS = 'SUBJECT_FILES_ERROR_PROCESS'

export const SUBJECT_ALL_COMMENTS_INFO_PROCESS = 'SUBJECT_ALL_COMMENTS_INFO_PROCESS'
export const SUBJECT_ALL_COMMENTS_ERROR_PROCESS = 'SUBJECT_ALL_COMMENTS_ERROR_PROCESS'

export const SUBJECT_COMMENTS_POST_PROCESS = 'SUBJECT_COMMENTS_POST_PROCESS'
export const SUBJECT_COMMENTS_POST_ERROR_PROCESS = 'SUBJECT_COMMENTS_POST_ERROR_PROCESS'
