export const DATASET_FILTERS_ALL_INFO_PROCESS = 'DATASET_FILTERS_ALL_INFO_PROCESS'
export const DATASET_FILTERS_ALL_ERROR_PROCESS = 'DATASET_FILTERS_ALL_ERROR_PROCESS'

export const USER_FILTER_INFO_PROCESS = 'USER_FILTER_INFO_PROCESS'
export const USER_FILTER_ERROR_PROCESS = 'USER_FILTER_ERROR_PROCESS'