export const FILE_DOWNLOAD_INFO_PROCESS = 'FILE_DOWNLOAD_INFO_PROCESS'
export const FILE_DOWNLOAD_ERROR_PROCESS = 'FILE_DOWNLOAD_ERROR_PROCESS'

export const FILE_UPLOAD_INFO_PROCESS = 'FILE_UPLOAD_INFO_PROCESS'
export const FILE_UPLOAD_ERROR_PROCESS = 'FILE_UPLOAD_ERROR_PROCESS'

export const FILE_HEADER_INFO_PROCESS = 'FILE_HEADER_INFO_PROCESS'
export const FILE_HEADER_ERROR_PROCESS = 'FILE_HEADER_ERROR_PROCESS'