export const USER_REPORTS_POST_PROCESS = 'USER_REPORTS_POST_PROCESS'
export const USER_REPORTS_POST_ERROR_PROCESS = 'USER_REPORTS_POST_ERROR_PROCESS'

export const USER_REPORTS_DELETE_PROCESS = 'USER_REPORTS_DELETE_PROCESS'
export const USER_REPORTS_DELETE_ERROR_PROCESS = 'USER_REPORTS_DELETE_ERROR_PROCESS'

export const USER_REPORTS_INFO_PROCESS = 'USER_REPORTS_INFO_PROCESS'
export const USER_REPORTS_INFO_ERROR_PROCESS = 'USER_REPORTS_INFO_ERROR_PROCESS'