export const CREATE_WORKSPACE_INFO_PROCESS = 'CREATE_WORKSPACE_INFO_PROCESS'
export const CREATE_WORKSPACE_ERROR_PROCESS = 'CREATE_WORKSPACE_ERROR_PROCESS'

export const EXECUTE_PIPELINE_INFO_PROCESS = 'EXECUTE_PIPELINE_INFO_PROCESS'
export const EXECUTE_PIPELINE_ERROR_PROCESS = 'EXECUTE_PIPELINE_ERROR_PROCESS'

export const USER_PIPELINE_INFO_PROCESS = 'USER_PIPELINE_INFO_PROCESS'
export const USER_PIPELINE_ERROR_PROCESS = 'USER_PIPELINE_ERROR_PROCESS'

export const USER_PIPELINE_byID_INFO_PROCESS = 'USER_PIPELINE_byID_INFO_PROCESS'
export const USER_PIPELINE_byID_ERROR_PROCESS = 'USER_PIPELINE_byID_ERROR_PROCESS'

export const FILE_UPLOAD_INFO_PROCESS = 'FILE_UPLOAD_INFO_PROCESS'
export const FILE_UPLOAD_ERROR_PROCESS = 'FILE_UPLOAD_ERROR_PROCESS'