export const ALL_USERS_INFO_PROCESS = 'ALL_USERS_INFO_PROCESS'
export const ALL_USERS_ERROR_PROCESS='ALL_USERS_ERROR_PROCESS'

export const USER_COMMENTS_ADD_PROCESS = 'USER_COMMENTS_ADD_PROCESS'
export const USER_COMMENTS_DELETE_PROCESS='USER_COMMENTS_DELETE_PROCESS'

export const USER_COMMENTS_INFO_PROCESS = 'USER_COMMENTS_INFO_PROCESS'
export const USER_COMMENTS_ERROR_PROCESS = 'USER_COMMENTS_ERROR_PROCESS'


